version: "3"
services:
  node:
    build: .
    command: "yarn dev"
    working_dir: /usr/app
    environment:
      - NODE_ENV=production
    expose:
      - "1337"
    ports:
      - "1337:1337"
